### ISSUE TITLE
navigation with redux, Invariant Violation: should be set

### ISSUE THREAD

**Issue by jamalx31** [react-navigation/react-navigation-redux-helpers#63]
works with react-navigation v2.17.0 but not 2.18.1
https://github.com/react-navigation/react-navigation/issues/5170

**Comment by Ashoat** [comment]
Thanks for the report! `react-navigation-redux-helpers@2.0.7` should fix this.

**Comment by ws7one** [comment]
With the following dependencies its working fine

```
  "dependencies": {
    "axios": "^0.18.0",
    "eslint-config-rallycoding": "^3.2.0",
    "numeral": "^2.0.6",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^0.19.1",
    "react-native-highcharts": "^1.0.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.9.0",
    "react-navigation-material-bottom-tabs": "^0.3.0",
    "react-navigation-redux-helpers": "^2.0.4",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.4.1",
    "react-test-renderer": "16.3.1"
  }
```

but with more latest versions such as follows, it fails

```
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "axios": "^0.18.0",
    "eslint-config-rallycoding": "^3.2.0",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
    "react-native-elements": "^0.19.1",
    "react-native-vector-icons": "^6.0.2",
    "react-navigation": "^2.18.1",
    "react-navigation-material-bottom-tabs": "^0.4.0",
    "react-navigation-redux-helpers": "^2.0.4",
    "react-redux": "^5.0.7",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
```

The following error is what i get.

![screenshot_1540994285](https://user-images.githubusercontent.com/41139390/47792949-1f270b80-dd43-11e8-8514-1798e49f7c45.png)

Not sure why is this closed, is there a fixed solution for this, because i have tried it with
"react-navigation-redux-helpers": "^2.0.4",
"react-navigation-redux-helpers": "^2.0.6",
"react-navigation-redux-helpers": "^2.0.7",

none of them fixed it for me

**Comment by Ashoat** [comment]
@ws7one you probably didn’t succeed in updating the package. Try again, this time making sure `node_modules/react-navigation-redux-helpers/package.json` reflects the version you claim to have.

**Comment by ws7one** [comment]
This is the current package.jason that i have

```
"dependencies": {
    "@babel/runtime": "^7.1.2",
    "axios": "^0.18.0",
    "eslint-config-rallycoding": "^3.2.0",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
    "react-native-elements": "^0.19.1",
    "react-native-vector-icons": "^6.0.2",
    "react-navigation": "^2.18.1",
    "react-navigation-material-bottom-tabs": "^0.4.0",
    "react-navigation-redux-helpers": "^2.0.7",
    "react-redux": "^5.0.7",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
```

and the result is still the same
![screenshot_1540994937](https://user-images.githubusercontent.com/41139390/47793592-a628b380-dd44-11e8-87e5-51536e0e297c.png)

**Comment by ggdegreat** [comment]
this helper doesn't worked for React Navigation v3.0

**Comment by shitou9999** [comment]
same question，v3 and react-navigation-redux-helpers@2.0.9

**Comment by Ashoat** [comment]
I can investigate further if you can provide an [MCVE](https://stackoverflow.com/help/mcve) that reproduces the issue, in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub.

**Comment by jannes-io** [comment]
Seems like 6 months later we're still having the same issues. Any updates on this?
